#!/usr/bin/env python

import os
import click
from valuestools import valuestools

tempdir = os.environ['HELM_PLUGIN_DIR'] + "/charts/"
extractpath = tempdir + "extract/"

# Fetch helm chart to temp dir
@click.command()
@click.argument('chartname')
def chart(chartname):

  setupsuccessful = valuestools.setup(tempdir)

  if not setupsuccessful:
    click.echo("Could not locate values.yaml in current directory, exiting!")
    exit()

  click.echo("Getting values from " + chartname)
  
  tarfiles = valuestools.getchart(tempdir, chartname)

  valuesfilepath = valuestools.verifyChart(tarfiles)

  # Extract if values.yaml exists
  if valuesfilepath:
    downloadedtar.extract(valuesfilepath, path=extractpath)
  else:
    click.echo("Could not locate values.yaml in downloaded chart, exiting!")
    valuestools.deleteFolder(tempdir)
    exit()

  # Open downloaded values and append with indent to values file in current directory
  isupdated = valuestools.appendValues(extractpath)

  if isupdated:
    click.echo("Values file updated with values from the " + chartname + " chart")

  # Clean up
  valuestools.deleteFolder(tempdir)

if __name__ == '__main__':
  chart()
